# Generated by Django 4.1.3 on 2022-11-16 23:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locations', '0002_route_place_route'),
    ]

    operations = [
        migrations.CreateModel(
            name='myRoute',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('palces', models.ManyToManyField(blank=True, null=True, to='locations.route')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
