# Generated by Django 4.1.3 on 2022-11-17 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_remove_place_route_route_places'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myroute',
            name='palces',
            field=models.ManyToManyField(blank=True, to='locations.route'),
        ),
    ]
