# Generated by Django 4.1.3 on 2022-11-17 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_myroute_palces'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myroute',
            old_name='palces',
            new_name='routes',
        ),
    ]
