# Generated by Django 4.1.3 on 2022-11-17 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_remove_place_route_route_places'),
        ('users', '0003_rename_palces_myroute_routes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myroute',
            name='routes',
        ),
        migrations.AddField(
            model_name='myroute',
            name='places',
            field=models.ManyToManyField(blank=True, to='locations.place'),
        ),
    ]
