# Generated by Django 4.1.3 on 2022-11-18 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_remove_place_route_route_places'),
        ('users', '0004_remove_myroute_routes_myroute_places'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myroute',
            name='places',
        ),
        migrations.AddField(
            model_name='myroute',
            name='places',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='locations.place'),
            preserve_default=False,
        ),
    ]
