# Generated by Django 4.1.3 on 2022-11-18 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_myroute_places_myroute_places'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myroute',
            old_name='places',
            new_name='place',
        ),
    ]
