# Generated by Django 4.1.3 on 2022-11-17 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_route_place_route'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='route',
        ),
        migrations.AddField(
            model_name='route',
            name='places',
            field=models.ManyToManyField(blank=True, to='locations.place'),
        ),
    ]
